# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 745)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.contenedor = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.contenedor.sizePolicy().hasHeightForWidth())
        self.contenedor.setSizePolicy(sizePolicy)
        self.contenedor.setObjectName("contenedor")
        self.titulo = QtWidgets.QLabel(self.contenedor)
        self.titulo.setGeometry(QtCore.QRect(50, 10, 1081, 81))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.table_variantes = QtWidgets.QTableView(self.contenedor)
        self.table_variantes.setGeometry(QtCore.QRect(610, 160, 531, 171))
        self.table_variantes.setStyleSheet("")
        self.table_variantes.setObjectName("table_variantes")
        self.table_variantes.horizontalHeader().setVisible(True)
        self.table_variantes.horizontalHeader().setCascadingSectionResizes(True)
        self.table_variantes.horizontalHeader().setSortIndicatorShown(False)
        self.table_variantes.verticalHeader().setCascadingSectionResizes(False)
        self.economia_label = QtWidgets.QLabel(self.contenedor)
        self.economia_label.setGeometry(QtCore.QRect(610, 340, 531, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.economia_label.setFont(font)
        self.economia_label.setStyleSheet(
            "border:2px solid black; background: white; border-radius:10px")
        self.economia_label.setObjectName("economia_label")
        self.line = QtWidgets.QFrame(self.contenedor)
        self.line.setGeometry(QtCore.QRect(590, 110, 16, 601))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.titulo_2 = QtWidgets.QLabel(self.contenedor)
        self.titulo_2.setGeometry(QtCore.QRect(640, 90, 471, 81))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_2.setFont(font)
        self.titulo_2.setStyleSheet("")
        self.titulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_2.setObjectName("titulo_2")
        self.calcular_button = QtWidgets.QPushButton(self.contenedor)
        self.calcular_button.setGeometry(QtCore.QRect(690, 650, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.calcular_button.setFont(font)
        self.calcular_button.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calcular_button.setStyleSheet(
            "border:2px solid black; background: white; border-radius:10px")
        self.calcular_button.setObjectName("calcular_button")
        self.flujo_vapor_entrada_label = QtWidgets.QLabel(self.contenedor)
        self.flujo_vapor_entrada_label.setGeometry(
            QtCore.QRect(610, 430, 531, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.flujo_vapor_entrada_label.setFont(font)
        self.flujo_vapor_entrada_label.setStyleSheet(
            "border:2px solid black; background: white; border-radius:10px")
        self.flujo_vapor_entrada_label.setObjectName(
            "flujo_vapor_entrada_label")
        self.input_numero_efectos = QtWidgets.QLineEdit(self.contenedor)
        self.input_numero_efectos.setGeometry(QtCore.QRect(259, 120, 261, 42))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_numero_efectos.sizePolicy().hasHeightForWidth())
        self.input_numero_efectos.setSizePolicy(sizePolicy)
        self.input_numero_efectos.setStyleSheet("border:1px solid black;\n"
                                                "border-radius: 10px;height:40px")
        self.input_numero_efectos.setInputMask("")
        self.input_numero_efectos.setObjectName("input_numero_efectos")
        self.label_numero_efecto = QtWidgets.QLabel(self.contenedor)
        self.label_numero_efecto.setGeometry(QtCore.QRect(20, 110, 221, 65))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_numero_efecto.sizePolicy().hasHeightForWidth())
        self.label_numero_efecto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_numero_efecto.setFont(font)
        self.label_numero_efecto.setObjectName("label_numero_efecto")
        self.selector_presion = QtWidgets.QComboBox(self.contenedor)
        self.selector_presion.setGeometry(QtCore.QRect(260, 230, 258, 42))
        self.selector_presion.setStyleSheet("border:1px solid black;\n"
                                            "border-radius: 10px;height:40px")
        self.selector_presion.setObjectName("selector_presion")
        self.label_tipo_presion = QtWidgets.QLabel(self.contenedor)
        self.label_tipo_presion.setGeometry(QtCore.QRect(20, 250, 259, 13))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_tipo_presion.sizePolicy().hasHeightForWidth())
        self.label_tipo_presion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tipo_presion.setFont(font)
        self.label_tipo_presion.setObjectName("label_tipo_presion")
        self.input_presion_efecto = QtWidgets.QLineEdit(self.contenedor)
        self.input_presion_efecto.setGeometry(QtCore.QRect(260, 280, 261, 42))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_presion_efecto.sizePolicy().hasHeightForWidth())
        self.input_presion_efecto.setSizePolicy(sizePolicy)
        self.input_presion_efecto.setStyleSheet("border:1px solid black;\n"
                                                "border-radius: 10px;height:40px")
        self.input_presion_efecto.setObjectName("input_presion_efecto")
        self.label_presion_efecto = QtWidgets.QLabel(self.contenedor)
        self.label_presion_efecto.setGeometry(QtCore.QRect(20, 280, 211, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_presion_efecto.sizePolicy().hasHeightForWidth())
        self.label_presion_efecto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_presion_efecto.setFont(font)
        self.label_presion_efecto.setWordWrap(True)
        self.label_presion_efecto.setObjectName("label_presion_efecto")
        self.input_flujo_alimentacion = QtWidgets.QLineEdit(self.contenedor)
        self.input_flujo_alimentacion.setGeometry(
            QtCore.QRect(260, 330, 261, 42))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_flujo_alimentacion.sizePolicy().hasHeightForWidth())
        self.input_flujo_alimentacion.setSizePolicy(sizePolicy)
        self.input_flujo_alimentacion.setStyleSheet("border:1px solid black;\n"
                                                    "border-radius: 10px;height:40px")
        self.input_flujo_alimentacion.setObjectName("input_flujo_alimentacion")
        self.label_flujo_alimentacion = QtWidgets.QLabel(self.contenedor)
        self.label_flujo_alimentacion.setGeometry(
            QtCore.QRect(20, 330, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_flujo_alimentacion.sizePolicy().hasHeightForWidth())
        self.label_flujo_alimentacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_flujo_alimentacion.setFont(font)
        self.label_flujo_alimentacion.setWordWrap(True)
        self.label_flujo_alimentacion.setObjectName("label_flujo_alimentacion")
        self.input_fraccion_masica_alimentacion = QtWidgets.QLineEdit(
            self.contenedor)
        self.input_fraccion_masica_alimentacion.setGeometry(
            QtCore.QRect(260, 390, 261, 42))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_fraccion_masica_alimentacion.sizePolicy().hasHeightForWidth())
        self.input_fraccion_masica_alimentacion.setSizePolicy(sizePolicy)
        self.input_fraccion_masica_alimentacion.setStyleSheet("border:1px solid black;\n"
                                                              "border-radius: 10px;height:40px")
        self.input_fraccion_masica_alimentacion.setObjectName(
            "input_fraccion_masica_alimentacion")
        self.label_fraccion_masica_alimentacion = QtWidgets.QLabel(
            self.contenedor)
        self.label_fraccion_masica_alimentacion.setGeometry(
            QtCore.QRect(20, 390, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_fraccion_masica_alimentacion.sizePolicy().hasHeightForWidth())
        self.label_fraccion_masica_alimentacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_fraccion_masica_alimentacion.setFont(font)
        self.label_fraccion_masica_alimentacion.setWordWrap(True)
        self.label_fraccion_masica_alimentacion.setObjectName(
            "label_fraccion_masica_alimentacion")
        self.input_fraccion_masica_producto = QtWidgets.QLineEdit(
            self.contenedor)
        self.input_fraccion_masica_producto.setGeometry(
            QtCore.QRect(260, 450, 258, 42))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_fraccion_masica_producto.sizePolicy().hasHeightForWidth())
        self.input_fraccion_masica_producto.setSizePolicy(sizePolicy)
        self.input_fraccion_masica_producto.setStyleSheet("border:1px solid black;\n"
                                                          "border-radius: 10px;height:40px")
        self.input_fraccion_masica_producto.setObjectName(
            "input_fraccion_masica_producto")
        self.label_fraccion_masica_producto = QtWidgets.QLabel(self.contenedor)
        self.label_fraccion_masica_producto.setGeometry(
            QtCore.QRect(20, 450, 201, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_fraccion_masica_producto.sizePolicy().hasHeightForWidth())
        self.label_fraccion_masica_producto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_fraccion_masica_producto.setFont(font)
        self.label_fraccion_masica_producto.setWordWrap(True)
        self.label_fraccion_masica_producto.setObjectName(
            "label_fraccion_masica_producto")
        self.input_temperatura_alimentacion = QtWidgets.QLineEdit(
            self.contenedor)
        self.input_temperatura_alimentacion.setGeometry(
            QtCore.QRect(260, 510, 261, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_temperatura_alimentacion.sizePolicy().hasHeightForWidth())
        self.input_temperatura_alimentacion.setSizePolicy(sizePolicy)
        self.input_temperatura_alimentacion.setStyleSheet("border:1px solid black;\n"
                                                          "border-radius: 10px;height:40px")
        self.input_temperatura_alimentacion.setObjectName(
            "input_temperatura_alimentacion")
        self.label_temperatura_alimentacion = QtWidgets.QLabel(self.contenedor)
        self.label_temperatura_alimentacion.setGeometry(
            QtCore.QRect(20, 500, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_temperatura_alimentacion.sizePolicy().hasHeightForWidth())
        self.label_temperatura_alimentacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_temperatura_alimentacion.setFont(font)
        self.label_temperatura_alimentacion.setWordWrap(True)
        self.label_temperatura_alimentacion.setObjectName(
            "label_temperatura_alimentacion")
        self.label_temperatura_vapor_saturado = QtWidgets.QLabel(
            self.contenedor)
        self.label_temperatura_vapor_saturado.setGeometry(
            QtCore.QRect(20, 160, 221, 76))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_temperatura_vapor_saturado.sizePolicy().hasHeightForWidth())
        self.label_temperatura_vapor_saturado.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_temperatura_vapor_saturado.setFont(font)
        self.label_temperatura_vapor_saturado.setAutoFillBackground(False)
        self.label_temperatura_vapor_saturado.setWordWrap(True)
        self.label_temperatura_vapor_saturado.setObjectName(
            "label_temperatura_vapor_saturado")
        self.input_temperatura_vapor_saturado = QtWidgets.QLineEdit(
            self.contenedor)
        self.input_temperatura_vapor_saturado.setGeometry(
            QtCore.QRect(260, 180, 261, 42))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_temperatura_vapor_saturado.sizePolicy().hasHeightForWidth())
        self.input_temperatura_vapor_saturado.setSizePolicy(sizePolicy)
        self.input_temperatura_vapor_saturado.setStyleSheet("border:1px solid black;\n"
                                                            "border-radius: 10px;height:40px")
        self.input_temperatura_vapor_saturado.setObjectName(
            "input_temperatura_vapor_saturado")
        MainWindow.setCentralWidget(self.contenedor)
        self.action12312 = QtWidgets.QAction(MainWindow)
        self.action12312.setObjectName("action12312")
        self.label_numero_efecto.setBuddy(self.input_numero_efectos)
        self.label_presion_efecto.setBuddy(self.input_presion_efecto)
        self.label_flujo_alimentacion.setBuddy(self.input_presion_efecto)
        self.label_fraccion_masica_alimentacion.setBuddy(
            self.input_presion_efecto)
        self.label_fraccion_masica_producto.setBuddy(self.input_presion_efecto)
        self.label_temperatura_alimentacion.setBuddy(self.input_presion_efecto)
        self.label_temperatura_vapor_saturado.setBuddy(
            self.input_temperatura_vapor_saturado)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate(
            "MainWindow", "Evaluacion y  conceptual de evaporadores de multiple efecto"))
        self.economia_label.setText(_translate(
            "MainWindow", "Economía del sistema :"))
        self.titulo_2.setText(_translate("MainWindow", "Solución agua-azúcar"))
        self.calcular_button.setText(_translate("MainWindow", "Calcular"))
        self.flujo_vapor_entrada_label.setText(_translate(
            "MainWindow", "Consumo de vapor saturado (kg/h) : "))
        self.input_numero_efectos.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.label_numero_efecto.setText(_translate(
            "MainWindow", "Número de efectos (n):"))
        self.label_tipo_presion.setText(
            _translate("MainWindow", "Tipo de presión:"))
        self.input_presion_efecto.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.label_presion_efecto.setText(_translate(
            "MainWindow", "Presión del último efecto (kPa):"))
        self.input_flujo_alimentacion.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.label_flujo_alimentacion.setText(_translate(
            "MainWindow", "Flujo de alimentación (kg/h):"))
        self.input_fraccion_masica_alimentacion.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.label_fraccion_masica_alimentacion.setText(_translate(
            "MainWindow", "Fracción másica del soluto en la alimentación:"))
        self.input_fraccion_masica_producto.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.label_fraccion_masica_producto.setText(_translate(
            "MainWindow", "Fracción másica del soluto en el producto:"))
        self.input_temperatura_alimentacion.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.label_temperatura_alimentacion.setText(
            _translate("MainWindow", "Temperatura de alimentación(c):"))
        self.label_temperatura_vapor_saturado.setText(_translate(
            "MainWindow", "Temperatura del vapor saturado (Tst):"))
        self.input_temperatura_vapor_saturado.setPlaceholderText(
            _translate("MainWindow", "Introduce el valor"))
        self.action12312.setText(_translate("MainWindow", "12312"))
